version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: code-porter-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: code_porter
      POSTGRES_USER: code_porter
      POSTGRES_PASSWORD: code_porter
    volumes:
      - code_porter_pg_data:/var/lib/postgresql/data

volumes:
  code_porter_pg_data:
